trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Android_Build
  displayName: "Build Android BSP"
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - checkout: self

    - script: |
        echo "Starting Android BSP build..."
        chmod +x build.sh
        ./build.sh
      displayName: "Run Android build.sh"

- stage: QA_Tests
  displayName: "Run QA Scripts"
  dependsOn: Android_Build
  jobs:
  - job: Tests
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'

    - checkout: self

    - script: |
        echo "Running internet test..."
        python3 QA_Scriprts/test_internet.py
      displayName: "Run Internet Test"

    - script: |
        echo "Running USB test..."
        python3 QA_Scriprts/test_usb.py
      displayName: "Run USB Test"