trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Checkout
- checkout: self
  displayName: "Checkout source code"

# Install deps
- script: |
    sudo apt-get update
    sudo apt-get install -y gawk wget git diffstat unzip texinfo \
      gcc-multilib build-essential chrpath socat cpio python3 python3-pip \
      python3-pexpect xz-utils debianutils iputils-ping
    pip3 install pytest
  displayName: "Install Yocto & Python dependencies"

# Build Android
- script: |
    echo "=== Building Android BSP ==="
    cd Android
    chmod +x build.sh
    ./build.sh
  displayName: "Build Android BSP"

# Build Yocto
- script: |
    echo "=== Building Yocto BSP ==="
    cd Yocto
    chmod +x build-yocto.sh
    ./build-yocto.sh
  displayName: "Build Yocto BSP"

# Run QA Tests
- script: |
    echo "=== Running QA Scripts ==="
    cd QA_Scriprts   # check folder spelling!
    python3 test_internet.py
    python3 test_usb.py
  displayName: "Execute QA Tests"