trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Checkout
- checkout: self
  displayName: "Checkout source code"

# Install deps
- script: |
    sudo apt-get update
    sudo apt-get install -y gawk wget git diffstat unzip texinfo \
      gcc-multilib build-essential chrpath socat cpio python3 python3-pip \
      python3-pexpect xz-utils debianutils iputils-ping
    pip3 install pytest
  displayName: "Install Yocto & Python dependencies"

# Build Android
- script: |
    echo "=== Building Android BSP ==="
    cd Android
    chmod +x build.sh
    ./build.sh
  displayName: "Build Android BSP"

# Build Yocto
- script: |
    echo "=== Building Yocto BSP ==="
    cd Yocto
    chmod +x build-yocto.sh
    ./build-yocto.sh
  displayName: "Build Yocto BSP"

# Run QA Tests with pytest
- script: |
    echo "=== Running QA Scripts ==="
    pytest QA_Scriprts/ --junitxml=results.xml
  displayName: "Execute QA Tests"

# Publish QA Test Results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/results.xml'
    testRunTitle: 'QA Test Results'

# Publish Build Artifacts
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'Android/out'     # adjust to actual output
    artifactName: 'Android_Build'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'Yocto/out'       # adjust to actual output
    artifactName: 'Yocto_Build'
