trigger:
- main   # run pipeline on push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Check out repo
- checkout: self
  displayName: "Checkout source code"

# Step 2: Install dependencies (Yocto & Python)
- script: |
    sudo apt-get update
    sudo apt-get install -y gawk wget git diffstat unzip texinfo \
      gcc-multilib build-essential chrpath socat cpio python3 python3-pip \
      python3-pexpect xz-utils debianutils iputils-ping
    pip3 install pytest
  displayName: "Install Yocto & Python dependencies"

# Step 3: Build Android BSP
- script: |
    echo "=== Building Android BSP ==="
    cd Android
    chmod +x build.sh
    ./build.sh
  displayName: "Build Android BSP"

# Step 4: Build Yocto BSP
- script: |
    echo "=== Building Yocto BSP ==="
    cd Yocto
    chmod +x build-yocto.sh
    ./build-yocto.sh
  displayName: "Build Yocto BSP"

# Step 5: Run QA Tests
- script: |
    echo "=== Running QA Scripts ==="
    cd QA_Scriprts   # <-- fix if folder is QA_Scripts
    python3 test_internet.py
    python3 test_usb.py
  displayName: "Execute QA Tests"